version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
#      - MONGO_DATA_DIR=/data/db
#      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=personal
    volumes:
      - ./temp/data/db:/data/db
    ports:
      - 27018:27017
    command: mongod --logpath=/dev/null # --quiet

  web:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    ports:
      - "8080:8080"
    depends_on:
      - mongodb